### ISSUE TITLE
Feature Request: add remediation tab as second tab in spreadsheet

### ISSUE THREAD

**Issue by TheBlindHacker** [interference-security/nessus_parse#1]
Can you add a remediation tab, as the second tab, that contains the Severity, Vulnerability name, Description of vulnerability, Solution, Occurrences, IP's found on.

**Comment by interference-security** [comment]
This script has not been developed by me. Due to which this request cannot be fulfilled at this time. Credit for this script goes to http://www.melcara.com/archives/253
