### ISSUE TITLE
Can't call method "add_worksheet" on an undefined value at parse_nessus_xml.v24.pl line 1653

### ISSUE THREAD

**Issue by ranjithkoolath** [interference-security/nessus_parse#2]
I am getting the following error:

`C:\Users\iam.windows\Desktop\strawberry-perl-5.32.1.1-64bit-portable>perl parse_nessus_xml.v24.pl -d nessus
These are the new features with version 24
1.  Fix regex \Q\E line est 1477,1484 v22
2.  Removing plugin 33929 from High Vulns calculation
3.  Removed Compliance from being part of High Vuln Calculation
4.  Version 23 Skipped
5.  reordered vuln data processing to not use as much memory.
The target directory is "nessus".

################################################################################
                            NESSUS PARSER V0.24
################################################################################

 Pause for Testing before reading data
Creating Spreadsheet Data
---------------  MOVE THE POLICY ARRAYS TO THE TOP

Creating Nessus Report Spreadsheet
Can't call method "add_worksheet" on an undefined value at parse_nessus_xml.v24.pl line 1653.
C:\Users\iam.windows\Desktop\strawberry-perl-5.32.1.1-64bit-portable>`

How can I change the $dir value to a specific one? lets say to "C:\Users\iam.windows\Desktop\nessus_report"

**Comment by interference-security** [comment]
Nessus Parser has not been developed by me. It has been mirrored on this repository. You can find the author's information here: http://www.melcara.com/archives/253.

If you are able to fix this bug, please submit a PR here or contact the author. Thanks.
